namespace TheLastStand.Serialization.Achievements;

public class SerializedAchievements
{
	public SerializedAchievementUnlocker Stun50EnemiesNightAchievementUnlocker;

	public SerializedAchievementUnlocker Crit20EnemiesTurnAchievementUnlocker;

	public SerializedAchievementUnlocker PerfectWinAchievementUnlocker;
}
